docs(v2 data engine): add V2 Data Engine CPU Mask
longhorn/website pull request #1002
Opened 2024-10-15 03:20 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#8835

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-10-15 14:42 UTC, jhkrug requested changes
A couple of tiny suggestions for you to consider. Thanks.

2024-10-15 14:54 UTC, innobead requested changes
LGTM, just one comment.

2024-10-15 14:54 UTC, innobead commented on content/docs/1.8.0/v2-data-engine/features/configurable-cpu-cores.md
> +For node-specific CPU core allocation, update the engine's `spec.dataEngineSpec.v2.cpuMask` field with a hexadecimal encoded string. By default, this value is empty, and the v2 data engine will use t
```suggestion
For node-specific CPU core allocation, update the `spec.dataEngineSpec.v2.cpuMask` field of the instance manager with a hexadecimal encoded string. By default, this value is empty, and the v2 data engine will use the global setting specified by `v2-data-engine-cpu-mask`. When a per-node configuration is set, the v2 data engine will prioritize this value over the global setting for that specific node.
```

2024-10-16 07:33 UTC, jhkrug approved these changes
lgtm

2024-10-16 08:06 UTC, merged