docs: add a notice prohibiting retention policies on backup targets
longhorn/website pull request #1010
Opened 2024-11-13 05:00 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9795

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-11-13 07:19 UTC, innobead approved these changes
Technically LGTM.

2024-11-13 11:53 UTC, jhkrug requested changes
Some minor suggestions for your consideration. Thanks.

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. **Any retention policy directly on the backup store is strictly prohibited**.
```suggestion
> - The lifecycle of Longhorn backups within the backup store is managed by Longhorn. **Any retention policy on the backup store is prohibited**.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - Longhorn will attempt to clean up the backup-related custom resources in the following scenarios:
```suggestion
> - Longhorn attempts to clean up the backup-related custom resources in the following scenarios:
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.6.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +>   - An empty response from the NFS server due to a brief server downtime.
Is the brevity of the server downtime relevant here?
```suggestion
>   - An empty response from the NFS server due to server downtime.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. Any retention policy directly on the backup store is strictly prohibited.
```suggestion
> The lifecycle of Longhorn backups within the backup store is managed by Longhorn. Any retention policy on the backup store is prohibited.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. **Any retention policy directly on the backup store is strictly prohibited**.
```suggestion
> - The lifecycle of Longhorn backups within the backup store is managed by Longhorn. **Any retention policy on the backup store is prohibited**.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - Longhorn will attempt to clean up the backup-related custom resources in the following scenarios:
```suggestion
> - Longhorn attempts to clean up the backup-related custom resources in the following scenarios:
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +>   - An empty response from the NFS server due to a brief server downtime.
```suggestion
>   - An empty response from the NFS server due to server downtime.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. **Any retention policy directly on the backup store is strictly prohibited**.
```suggestion
> - The lifecycle of Longhorn backups within the backup store is managed by Longhorn. **Any retention policy on the backup store is prohibited**.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - Longhorn will attempt to clean up the backup-related custom resources in the following scenarios:
```suggestion
> - Longhorn attempts to clean up the backup-related custom resources in the following scenarios:
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +>   - An empty response from the NFS server due to a brief server downtime.
```suggestion
>   - An empty response from the NFS server due to server downtime.
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.7.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +>   The backup information will be resynchronized during the next polling interval. For more information, see [#9530](https://github.com/longhorn/longhorn/issues/9530).
```suggestion
>   The backup information is resynchronized during the next polling interval. For more information, see [#9530](https://github.com/longhorn/longhorn/issues/9530).
```

2024-11-13 11:53 UTC, jhkrug commented on content/docs/1.8.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +> - The lifecycle of Longhorn backups within the backup store is entirely managed by Longhorn. **Any retention policy directly on the backup store is strictly prohibited**.
```suggestion
> - The lifecycle of Longhorn backups within the backup store is managed by Longhorn. **Any retention policy on the backup store is prohibited**.
```

2024-11-14 09:20 UTC, jhkrug approved these changes
lgtm.

2024-11-14 09:43 UTC, innobead approved these changes

2024-11-14 09:43 UTC, merged