chore: archive v1.5.x
longhorn/website pull request #1015
Opened 2024-12-05 06:07 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue #

1.5.x is EOL

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-12-10 14:55 UTC, derekbit commented
> @derekbit PR checks failed.

Fixed and ready for review.

2024-12-12 07:30 UTC, derekbit commented
ping @jhkrug

2024-12-12 15:05 UTC, innobead requested changes

2024-12-12 15:05 UTC, innobead commented on config.toml
> +archived_versions = ["1.5.5", "1.5.4", "1.5.3", "1.5.2", "1.5.1", "1.5.0", "1.4.4", "1.4.3", "1.4.2", "1.4.1", "1.4.0", "1.3.3", "1.3.2", "1.3.1", "1.3.0", "1.2.6", "1.1.3"]
For 1.4 and 1.3, let's just keep the last version, 1.4.4 and 1.3.3.

2024-12-14 12:30 UTC, innobead approved these changes

2024-12-14 12:30 UTC, merged

2024-12-14 12:31 UTC, innobead commented
This is a config change w/o doc updates. Merged w/o @longhorn/doc review.