Add document for the feature `Allow Recurring Job While Volume Is Detached`
longhorn/website pull request #204
Opened 2020-10-06 07:49 UTC by PhanLe1010

longhorn/longhorn#1509

2020-10-06 07:52 UTC, PhanLe1010 commented on content/docs/1.1.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +          "cron":"*/2 * * * *",
Golang automatically formats this code

2020-10-07 20:09 UTC, yasker requested changes
Current part LGTM. But we need to add more explanation on when will the scheduled snapshot/backup skipped.

2020-10-07 21:30 UTC, PhanLe1010 commented
@yasker Added the explanation

2020-10-07 21:55 UTC, yasker approved these changes

2020-10-07 21:55 UTC, merged