Docs for the new feature Backing image
longhorn/website pull request #259
Opened 2021-01-29 13:31 UTC by shuo-wu

longhorn/longhorn#2006

2021-02-18 01:38 UTC, yasker requested changes
PR should be made against v1.1.1 branch v1.1.1 directory.

Otherwise LGTM.

2021-02-22 07:06 UTC, shuo-wu commented
Updated. Wait for @catherineluse review then?

2021-02-22 20:41 UTC, catherineluse approved these changes

2021-02-22 23:09 UTC, yasker approved these changes

2021-02-22 23:10 UTC, yasker commented
Merged, thanks @catherineluse

2021-02-22 23:10 UTC, merged