Add example to create AWS S3 credential via kubectl command
longhorn/website pull request #261
Opened 2021-02-03 08:52 UTC by jenting

2021-02-03 23:51 UTC, yasker requested changes

2021-02-03 23:51 UTC, yasker commented on content/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
The line above says `put the following key-value pairs in the secret`, which we should update.

2021-02-03 23:51 UTC, yasker commented on content/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +    kubectl create secret generic aws-secret --from-literal=AWS_ACCESS_KEY_ID=<your_aws_access_key_id> --from-literal=AWS_SECRET_ACCESS_KEY=<your_aws_secret_access_key> -n longhorn-system
Need to let users know they can choose the secret name (instead of hard coding `aws-secret`).

2021-02-05 00:51 UTC, yasker approved these changes
LGTM. Let me know if it's ready to merge.

2021-02-05 02:19 UTC, jenting commented
> LGTM. Let me know if it's ready to merge.

@yasker This is ready to be merged, thank you.

2021-02-05 18:40 UTC, merged