Add document for node selector feature
longhorn/website pull request #287
Opened 2021-04-15 01:10 UTC by PhanLe1010

longhorn/longhorn#2199

2021-04-15 05:54 UTC, PhanLe1010 commented
Just in case you haven't notice, we can preview this PR on a live website by clicking on the highlighted linked as shown in the picture:
<img width="858" alt="Screen Shot 2021-04-14 at 10 51 15 PM" src="https://user-images.githubusercontent.com/22139961/114820714-4b4c7080-9d74-11eb-818d-16da7889c7ac.png">

2021-04-15 06:17 UTC, innobead requested changes
LGTM, just some comments needed to resolve.

2021-04-15 06:17 UTC, innobead commented on content/docs/1.1.1/advanced-resources/deploy/node-selector.md
> +### Setting up Taints and Tolerations After Longhorn has been installed
```suggestion
### Setting up Node Selector After Longhorn has been installed
```

2021-04-15 06:17 UTC, innobead commented on content/docs/1.1.1/advanced-resources/deploy/node-selector.md
> +   * Stop all workload and detach all Longhorn volumes. Make sure all Longhorn volumes are `detached`
```suggestion
   * Stop all workloads and detach all Longhorn volumes. Make sure all Longhorn volumes are `detached`.
```

2021-04-15 06:18 UTC, innobead commented
cc @catherineluse please help review and approve. thanks.

2021-04-15 06:24 UTC, PhanLe1010 commented on content/docs/1.1.1/advanced-resources/deploy/node-selector.md
> +### Setting up Taints and Tolerations After Longhorn has been installed
Thank you. Fixed

2021-04-15 06:25 UTC, PhanLe1010 commented on content/docs/1.1.1/advanced-resources/deploy/node-selector.md
> +   * Stop all workload and detach all Longhorn volumes. Make sure all Longhorn volumes are `detached`
Thank you. Fixed

2021-04-15 06:27 UTC, innobead approved these changes

2021-04-16 03:22 UTC, shuo-wu approved these changes

2021-04-19 05:23 UTC, jenting commented
> Just in case you haven't noticed, we can preview this PR on a live website by clicking on the highlighted linked as shown in the picture:
> <img alt="Screen Shot 2021-04-14 at 10 51 15 PM" width="858" src="https://user-images.githubusercontent.com/22139961/114820714-4b4c7080-9d74-11eb-818d-16da7889c7ac.png">

cool!!!

2021-04-20 07:04 UTC, merged