Add knowledge base when use Traefik 2.x as ingress controller
longhorn/website pull request #289
Opened 2021-04-20 04:10 UTC by jenting

#### Issues
https://github.com/longhorn/longhorn/issues/1442

2021-04-20 04:14 UTC, innobead approved these changes
LGTM

2021-04-20 04:15 UTC, innobead commented
cc @meldafrawi

2021-04-20 10:18 UTC, innobead requested changes
LGTM, minor changes required.

2021-04-20 10:18 UTC, innobead commented on content/kb/troubleshooting-traefik-2.x-as-ingress-controller.md
> +The API requests would change the protocol between HTTPS/WSS, change the protocol between HTTPS/WSS would lead to a CORS problem.
```suggestion
The API requests would change the protocol between HTTPS/WSS, and the change would lead to a CORS problem.
```

2021-04-20 10:18 UTC, innobead commented on content/kb/troubleshooting-traefik-2.x-as-ingress-controller.md
> +The Traefik 2.x ingress controller does not setting the websocket headers.
```suggestion
The Traefik 2.x ingress controller does not set the WebSocket headers.
```

2021-04-20 10:18 UTC, innobead commented on content/kb/troubleshooting-traefik-2.x-as-ingress-controller.md
> +1. We add the following middleware to the route for the Longhorn GUI.
```suggestion
1. Adds the following middleware to the route for the Longhorn frontend service.
```

2021-04-20 22:58 UTC, catherineluse submitted a review, later dismissed
After David's suggested changes are incorporated, LGTM.

2021-04-22 04:59 UTC, innobead approved these changes

2021-04-22 04:59 UTC, merged