Add "Orphaned Data Automatic Deletion"
longhorn/website pull request #566
Opened 2022-08-17 02:33 UTC by derekbit

[Longhorn 4432](https://github.com/longhorn/longhorn/issues/4432)

Signed-off-by: Derek Su <derek.su@suse.com>

2022-08-17 07:35 UTC, innobead requested changes

2022-08-17 07:35 UTC, innobead commented on content/docs/1.3.0/references/settings.md
> +This setting allows Longhorn to automatically delete the `orphan` resource and its orphaned data.
```suggestion
This setting allows Longhorn to automatically delete the `orphan` resource and its orphaned data like volume replica. 
```

2022-08-18 01:17 UTC, derekbit commented on content/docs/1.3.0/references/settings.md
> +This setting allows Longhorn to automatically delete the `orphan` resource and its orphaned data.
Addressed. Thank you.

2022-08-18 01:54 UTC, innobead approved these changes

2022-08-18 01:54 UTC, merged