Longhorn Networking: add webhook and recovery backend
longhorn/website pull request #573
Opened 2022-08-25 02:43 UTC by derekbit

[Longhorn 4478
](https://github.com/longhorn/longhorn/issues/4478)
Signed-off-by: Derek Su <derek.su@suse.com>

2022-09-06 02:38 UTC, innobead commented on content/docs/1.3.1/references/networking.md
> +`Webhook Server` | 9443 | TCP
Why it has egress?

2022-09-06 02:39 UTC, innobead requested changes

2022-09-06 02:39 UTC, innobead commented on content/docs/1.3.1/references/networking.md
> +To | Port | Protocol
`From` instead of `To` for ingress

2022-09-06 02:39 UTC, innobead commented on content/docs/1.4.0/references/networking.md
> +To | Port | Protocol
From

2022-09-06 02:39 UTC, innobead commented on content/docs/1.4.0/references/networking.md
> +`Recovery Backend Server` | 9600 | TCP
Why it has egress?

2022-10-05 08:46 UTC, derekbit commented on content/docs/1.3.1/references/networking.md
> +`Webhook Server` | 9443 | TCP
Not needed. Removed, thank you.

2022-10-05 08:46 UTC, derekbit commented on content/docs/1.4.0/references/networking.md
> +`Recovery Backend Server` | 9600 | TCP
Not needed. Removed, thank you.

2022-10-05 08:46 UTC, derekbit commented on content/docs/1.4.0/references/networking.md
> +To | Port | Protocol
Updated, thank you.

2022-10-05 08:53 UTC, innobead approved these changes

2022-10-05 08:53 UTC, merged