Add CIFS backupstore
longhorn/website pull request #660
Opened 2023-01-12 13:44 UTC by derekbit

Longhorn/longhorn#3599

Signed-off-by: Derek Su <derek.su@suse.com>

2023-02-07 09:49 UTC, innobead requested changes
LGTM. Just one comment needed to resolve.

2023-02-07 09:49 UTC, innobead commented on content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +  kubectl -n longhorn-system delete secret cifs-secret
Remove this cleanup statement.

2023-02-07 09:50 UTC, innobead commented on content/docs/1.5.0/terminology.md
> +- [CRD](#crd)
This is another good example again to do the refactoring or a minor fix together with a new change. 

cc @longhorn/dev

2023-03-24 04:41 UTC, derekbit commented on content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
> +  kubectl -n longhorn-system delete secret cifs-secret
Updated. Thank you.

2023-03-24 04:46 UTC, innobead approved these changes

2023-03-24 04:46 UTC, merged