docs(recurring job): behavior changed
longhorn/website pull request #678
Opened 2023-03-21 01:55 UTC by mantissahz

Update `important-notes` for v1.3.3, v1.4.2 and v1.5.0.

Ref: longhorn/longhorn#4898

2023-03-22 00:38 UTC, mantissahz commented
cc @c3y1huang @innobead

2023-04-18 22:49 UTC, innobead requested changes
@mantissahz Please correct the doc as per the suggestions.

I did not make all the suggested changes, so you need to recheck this PR and fix them all.

2023-04-18 22:49 UTC, innobead commented on content/docs/1.3.3/deploy/important-notes/index.md
> +5. After the upgrade, the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain co
```suggestion
5. After the upgrade, the behavior of the recurring job types `Snapshot` and `Backup` will attempt to delete old snapshots first if they exceed the retained count before creating a new snapshot. Additionally, two new recurring job types have been introduced, `Snapshot Force Create` and `Backup Force Create`. They retain the original behavior of taking a snapshot or backup first before deleting outdated snapshots.
```

2023-04-18 22:49 UTC, innobead commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `backup`: periodically create snapshots then do backups except for old snapshots cleanup failed before creating new snapshots
```suggestion
  - `backup`: periodically create snapshots then do backups after cleaning up outdated snapshots
```

2023-04-18 22:49 UTC, innobead commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `snapshot`: periodically create snapshots except for old snapshots cleanup failed before creating new snapshots
```suggestion
  - `snapshot`: periodically create snapshots after cleaning up outdated snapshots
```

2023-04-18 22:49 UTC, innobead commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `snapshot-force-create`: periodically create snapshots even if old snapshots cleanup failed
```suggestion
  - `snapshot-force-create`: periodically create snapshots
```

2023-04-18 22:49 UTC, innobead commented on content/docs/1.4.2/deploy/important-notes/index.md
> +And the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain count, older snapsho
```suggestion
The behavior of the recurring job types `Snapshot` and `Backup` will attempt to delete old snapshots first if they exceed the retained count before creating a new snapshot. Additionally, two new recurring job types have been introduced, `Snapshot Force Create` and `Backup Force Create`. They retain the original behavior of taking a snapshot or backup first before deleting outdated snapshots.
```

2023-04-18 22:49 UTC, innobead commented on content/docs/1.5.0/deploy/important-notes/index.md
> +And the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain count, older snapsho
```suggestion
The behavior of the recurring job types `Snapshot` and `Backup` will attempt to delete old snapshots first if they exceed the retained count before creating a new snapshot. Additionally, two new recurring job types have been introduced, `Snapshot Force Create` and `Backup Force Create`. They retain the original behavior of taking a snapshot or backup first before deleting outdated snapshots.
```

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.3.3/deploy/important-notes/index.md
> +5. After the upgrade, the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain co
Modified. Thanks

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `backup`: periodically create snapshots then do backups except for old snapshots cleanup failed before creating new snapshots
Modified for all related files. Thanks

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `snapshot`: periodically create snapshots except for old snapshots cleanup failed before creating new snapshots
Modified for all related files. Thanks

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `snapshot-force-create`: periodically create snapshots even if old snapshots cleanup failed
Modified for all related files. Thanks

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.4.2/deploy/important-notes/index.md
> +And the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain count, older snapsho
Modified. Thanks

2023-04-19 02:14 UTC, mantissahz commented on content/docs/1.5.0/deploy/important-notes/index.md
> +And the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain count, older snapsho
Modified. Thanks

2023-04-19 02:15 UTC, mantissahz commented on content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
> +  - `backup`: periodically create snapshots then do backups except for old snapshots cleanup failed before creating new snapshots
Modified for all related files. Thanks

2023-04-19 02:15 UTC, mantissahz commented on content/docs/1.5.0/deploy/important-notes/index.md
> +And the behavior of recurring job task types `Snapshot` and `Backup` will be changed to check the number of old snapshots first. If the number of old snapshots exceeds the retain count, older snapsho
Modified. Thanks

2023-04-19 04:59 UTC, innobead approved these changes
LGTM.

2023-04-19 04:59 UTC, merged