doc: fix typo in multidisk document
longhorn/website pull request #702
Opened 2023-05-12 13:52 UTC by CNLHC

2023-05-15 14:55 UTC, ejweber requested changes
Thanks for the contribution, @CNLHC!

It looks like we documented the new default of 200 (changed from 500) on the Settings Reference page [as early as](https://github.com/longhorn/website/blob/d1e0f0e1766d7f332d729ebe33d3e61f3197f2fd/content/docs/archives/1.0.0/references/settings.md?plain=1#L154) `v1.0.0`, but we missed modifying this file. Would you be willing to make this change to `content/docs/<every_version_since_and_including_v1.0.0` so users on older versions aren't confused?

2023-05-16 00:54 UTC, CNLHC commented
@ejweber sure. I have changed all the typos since `v1.0.0`

2023-05-16 10:22 UTC, innobead requested changes
Just one change required, others LGTM.

2023-05-16 10:22 UTC, innobead commented on content/docs/1.5.0/volumes-and-nodes/multidisk.md
> +- `StorageOverProvisioningPercentage` defines the upper bound of `ScheduledStorage / (MaximumStorage - ReservedStorage)`. The default value is `200` (%). That means we can schedule a total of 750 GiB
From 1.5.0, we changed the provision percentage to 100 instead.

2023-05-16 13:16 UTC, innobead approved these changes

2023-05-16 13:16 UTC, merged