feat(metrics): longhorn_disk_status
longhorn/website pull request #786
Opened 2023-10-13 01:06 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/6858
https://github.com/longhorn/longhorn/issues/6873
https://github.com/longhorn/longhorn/issues/6872

2023-10-18 07:55 UTC, c3y1huang commented
cc @jillian-maroket , @innobead

2023-10-19 15:21 UTC, innobead approved these changes

2023-10-19 15:24 UTC, innobead requested changes

2023-10-19 15:24 UTC, innobead commented on content/docs/1.4.4/monitoring/metrics.md
> +| longhorn_disk_status | The status of this disk | longhorn_disk_status{condition="ready", disk="default-disk-ca0300000000"} |
Why there is no node label in the example?

2023-10-19 15:25 UTC, innobead commented
cc @jillian-maroket when reviewing PRs, if the PRs related to the upcoming release, we should treat them as high priority.

2023-10-20 08:12 UTC, jillian-maroket approved these changes
LGTM. Thanks!

2023-10-24 08:46 UTC, chriscchien approved these changes
LGTM

2023-10-24 09:11 UTC, innobead approved these changes

2023-10-24 09:11 UTC, merged