doc(telemetry): collect SPDK node disk type
longhorn/website pull request #807
Opened 2023-12-11 06:01 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/6033

2023-12-12 10:24 UTC, innobead requested changes

2023-12-12 10:24 UTC, innobead commented on content/docs/1.6.0/references/settings.md
> +- Number of volumes of each backup storage driver (v1, v2).
```suggestion
- Number of volumes of the backend storage driver in each data engine (v1, v2).
```

2023-12-13 09:53 UTC, jillian-maroket reviewed
Just a few nits.

2023-12-13 09:53 UTC, jillian-maroket commented on content/docs/1.6.0/references/settings.md
> +- Number of disk of each Longhorn disk type (block, filesystem).
```suggestion
- Number of disks for each Longhorn disk type (block, filesystem).
```

2023-12-13 09:53 UTC, jillian-maroket commented on content/docs/1.6.0/references/settings.md
> +- Number of volumes of the backend storage driver in each data engine (v1, v2).
```suggestion
- Number of volumes associated with the backend store driver in each data engine (v1, v2).
```

2023-12-15 02:15 UTC, jillian-maroket approved these changes

2023-12-15 02:30 UTC, innobead approved these changes

2023-12-15 02:30 UTC, merged