doc(volume): max volume size for the file system
longhorn/website pull request #831
Opened 2024-01-03 02:53 UTC by mantissahz

Descriptions of the maximum volume size for file systems.

Ref: longhorn/longhorn#7423

2024-01-03 03:18 UTC, jillian-maroket reviewed
Let me know if you have concerns about the changes.

2024-01-03 03:18 UTC, jillian-maroket commented on content/docs/1.6.0/volumes-and-nodes/expansion.md
> +- The expanded size should be smaller than the maximum file size of the file system, e.g., 16TiB for the `ext4` file system.
```suggestion
The expanded size must be less than the maximum file size allowed by the file system (for example, 16TiB for `ext4`).
```

2024-01-03 03:18 UTC, jillian-maroket commented on content/docs/1.6.0/volumes-and-nodes/volume-size.md
> +- The maximum volume size depends on the disk's file system, e.g., 16383 GiB for the `ext4` file system.
```suggestion
The maximum volume size is based on the disk's file system (for example, 16383 GiB for `ext4`).
```

2024-01-03 03:55 UTC, mantissahz commented on content/docs/1.6.0/volumes-and-nodes/expansion.md
> +- The expanded size should be smaller than the maximum file size of the file system, e.g., 16TiB for the `ext4` file system.
Modified. Thanks.

2024-01-03 03:55 UTC, mantissahz commented on content/docs/1.6.0/volumes-and-nodes/volume-size.md
> +- The maximum volume size depends on the disk's file system, e.g., 16383 GiB for the `ext4` file system.
Modified. Thanks.

2024-01-03 05:34 UTC, jillian-maroket approved these changes

2024-01-03 05:43 UTC, innobead requested changes
Please update 1.5.4 and 1.4.5 doc as well, as the fix should be backported.

2024-01-03 08:04 UTC, mantissahz commented
>Please update 1.5.4 and 1.4.5 doc as well

Updated 1.5.4 and 1.4.5 documents. Thanks.

2024-01-03 08:12 UTC, innobead approved these changes

2024-01-03 08:12 UTC, merged

2024-01-04 16:46 UTC, ejweber commented
I would suggest also updating any unarchived docs with this information. Users may be on an older version (e.g. 1.4.3) and only searching that relevant doc to understand why new volume attachment and/or expansion is failing. Even though the older versions won't have any enforcement, it helps troubleshooting.