Update Sles version
longhorn/website pull request #849
Opened 2024-01-16 21:45 UTC by khushboo-rancher

#### Which issue(s) this PR fixes:
Issue - https://github.com/longhorn/website/pull/842/files#r1451283819

#### What this PR does / why we need it: Update the Sles version for 1.5.x and 1.4.x branches

2024-01-16 23:10 UTC, innobead requested changes
Should update SLE Micro as well.

2024-01-17 02:02 UTC, khushboo-rancher commented
@innobead SLE micro version is updated.

2024-01-17 02:35 UTC, jillian-maroket approved these changes

2024-01-17 03:17 UTC, innobead approved these changes

2024-01-17 03:17 UTC, merged

2024-01-22 19:44 UTC, khushboo-rancher commented
https://github.com/longhorn/longhorn/issues/7666