doc(1.8.0): add DR volumes support for v2 data engine
longhorn/website pull request #977
Opened 2024-08-26 04:29 UTC by c3y1huang

#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#6613

#### What this PR does / why we need it:

Add DR volume support for the v2 data engine in the important note.

#### Special notes for your reviewer:

`None`

#### Additional documentation or context

`None`

2024-08-28 06:50 UTC, derekbit submitted a review, later dismissed
LGTM

2024-08-29 09:15 UTC, jhkrug requested changes
A small suggestion.

2024-08-29 09:15 UTC, jhkrug commented on content/docs/1.8.0/important-notes/_index.md
> +Disaster recovery volumes is supported since Longhorn v1.8.0.
```suggestion
Disaster recovery volumes are supported from Longhorn v1.8.0.
```

2024-08-30 03:35 UTC, c3y1huang commented on content/docs/1.8.0/important-notes/_index.md
> +Disaster recovery volumes is supported since Longhorn v1.8.0.
Updated, thank you!

2024-08-30 07:56 UTC, derekbit approved these changes
LGTM

2024-08-31 03:23 UTC, derekbit approved these changes

2024-08-31 03:24 UTC, merged