docs: describe new last replica timeout behavior
longhorn/website pull request #978
Opened 2024-08-26 19:21 UTC by ejweber

Longhorn 8711

#### Which issue(s) this PR fixes:

longhorn/longhorn#8711

#### What this PR does / why we need it:

We need to clarify how the behavior of the `engine-replica-timeout` setting changes in v1.7.1 and v1.8.0.

Per https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update, the actual setting definition stored in longhorn-manager should continue to be a one sentence description, so I think we only need to make the change here in the website.

I changed the heading from `Engine to Replica Timeout` to `Engine Replica Timeout` because the actual setting name is `engine-replica-timeout` and I think the "to" might be confusing to users looking for the setting to modify in their environments.

2024-08-29 09:22 UTC, jhkrug requested changes
If the suggestions are acceptable they are needed in 1.8.0 as well. Thanks.

2024-08-29 09:22 UTC, jhkrug commented on content/docs/1.7.1/references/settings.md
> +and 30 are allowed. Only in effect while there are I/O requests outstanding.
```suggestion
and 30 are allowed. The engine replica timeout is only in effect while there are I/O requests outstanding.
```

2024-08-29 09:22 UTC, jhkrug commented on content/docs/1.7.1/references/settings.md
> +This timeout only applies as-configured to additional/extra replicas. A v1 engine will not mark the final replica for a
Only one of 'additional' or 'extra' is needed.
```suggestion
This timeout only applies to additional replicas. A v1 engine will not mark the final replica for a
```

2024-08-29 15:01 UTC, ejweber commented
I made the requested changes in an amend.

2024-08-29 15:02 UTC, derekbit approved these changes
LGTM

2024-08-29 23:49 UTC, derekbit approved these changes

2024-08-29 23:50 UTC, derekbit commented
@ejweber Can you add it into the important notes? Thank you.

2024-08-30 07:47 UTC, derekbit approved these changes

2024-08-30 07:47 UTC, merged

2024-08-30 13:26 UTC, jhkrug requested changes
A suggestion.

2024-08-30 15:19 UTC, ejweber commented
Sorry @jhkrug. I was going back-and-forth about removing "as-configured", but in the end I decided to just follow your suggestion without comment. (I would not have resolved the conversation without discussion if I wasn't going to make the suggested changes directly.) It seems I messed up and pushed a version of my amend that didn't have your suggestion.

Looks like I need to update the important notes anyway, so we can catch it there.

2024-08-30 15:33 UTC, ejweber commented on content/docs/1.7.1/references/settings.md
> +This timeout only applies as-configured to additional replicas. A v1 engine will not mark the final replica for a
Sorry @jhkrug. I was going back-and-forth about removing "as-configured", but in the end I decided to just follow your suggestion without comment. (I would not have resolved the conversation without discussion if I wasn't going to make the suggested changes directly.) It seems I messed up and pushed a version of my amend that didn't include the suggestion after all.

Looks like I need to update the important notes anyway, so we can catch it there.

https://github.com/longhorn/website/pull/980