doc(1.8.0): add replica auto-balance to best-practice
longhorn/website pull request #993
Opened 2024-09-20 09:01 UTC by c3y1huang

#### Which issue(s) this PR fixes:

Issue `None`

#### What this PR does / why we need it:

Recommend setting the replica auto-balance setting option to least-effort as best practice for the production environment.

#### Special notes for your reviewer:

#### Additional documentation or context

https://suse.slack.com/archives/C02CLV7D2KH/p1726814707259759

2024-09-20 13:10 UTC, jhkrug requested changes
Small suggestion

2024-09-20 13:10 UTC, jhkrug commented on content/docs/1.8.0/best-practices.md
> +For production environments, we recommend to set Replica Auto-Balance to `least-effort`. This setting ensures that at least one replica is placed on a different node and in each zone, providing extra
```suggestion
For production environments, we recommend setting Replica Auto-Balance to `least-effort`. This setting ensures that at least one replica is placed on a different node in each zone, providing extra high availability (HA).
```

2024-09-24 12:02 UTC, jhkrug approved these changes
ok, lgtm

2024-09-25 02:22 UTC, innobead approved these changes
LGTM

2024-09-25 02:23 UTC, innobead commented
We can also add this to 1.7 and 1.6.

2024-09-25 02:44 UTC, innobead approved these changes

2024-09-25 02:44 UTC, merged