doc(node): add `KernelModulesLoaded` node condition
longhorn/website pull request #995
Opened 2024-10-01 02:33 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#9153

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-10-01 08:47 UTC, jhkrug requested changes
A very minor suggestion for your consideration.

2024-10-01 08:47 UTC, jhkrug commented on content/docs/1.7.2/nodes-and-volumes/nodes/node-conditions.md
> +  - `dm_crypt`: It is required for the volume and backing image encryption.
```suggestion
  - `dm_crypt`: Is required for the volume and backing image encryption.  
```

2024-10-01 08:47 UTC, jhkrug commented on content/docs/1.8.0/nodes-and-volumes/nodes/node-conditions.md
> +  - `dm_crypt`: It is required for the volume and backing image encryption.
```suggestion
  - `dm_crypt`: Is required for the volume and backing image encryption.  
```

2024-10-01 08:53 UTC, mantissahz commented on content/docs/1.7.2/nodes-and-volumes/nodes/node-conditions.md
> +  - `dm_crypt`: It is required for the volume and backing image encryption.
Modified. Thanks.

2024-10-01 08:53 UTC, mantissahz commented on content/docs/1.8.0/nodes-and-volumes/nodes/node-conditions.md
> +  - `dm_crypt`: It is required for the volume and backing image encryption.
Modified. Thanks.

2024-10-02 07:41 UTC, jhkrug approved these changes
lgtm

2024-10-09 04:37 UTC, merged